### ISSUE TITLE
Add "about" item in menu

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/DominicanWhoCodes#22]
![image](https://user-images.githubusercontent.com/5460365/68036985-21e17700-fc9d-11e9-9ded-47549da1881f.png)

**Comment by benjaminvar** [comment]
I would like to work on this issue.

**Comment by DannyFeliz** [comment]
@benjaminvar all yours

**Comment by benjaminvar** [comment]
Thanks.

**Comment by benjaminvar** [comment]
Done.
