### ISSUE TITLE
Configure a git hook to avoid commits with wrong formatting

### ISSUE THREAD

**Issue by DannyFeliz** [VueDominicana/DominicanWhoCodes#47]
Add the git precommit hook to avoid new commits with wrong formatting, here's a video showing how to do it. 
[Add ESLint & Prettier to VS Code for a Create React App](https://youtu.be/bfyI9yl3qfE?t=352)

**Comment by vyzaldysanchez** [comment]
I'll take this one, expect something later today or in the next day or two.

**Comment by DannyFeliz** [comment]
Fixed #48
